project:
  type: book
  output-dir: docs
  preview:
    browser: true
    navigate: true
  render: 
    - "*.qmd"
    - "contents/*.qmd"
    - "contents/*/*.qmd"
    - "contents/*/*/*.qmd"
    - "contents/*/*/*/*.qmd"
    - "contents/*/*/*/*/*.qmd"

book:
#  google-analytics:
#    tracking-id: ""
#    anonymize-ip: true
#    version: 4
#  comments: 
#    hypothesis:
#      theme: clean
#      openSidebar: true
  search:
    keyboard-shortcut: ["~", "/"]
    location: sidebar
  navbar:
    pinned: false
    collapse: true
    back-to-top-navigation: true
#  favicon: favicon.png
#  cover-image: cover-image.pdf
#  cover-image-alt: "Cover image."
  bread-crumbs: true
  sidebar:
    collapse-level: 2
    border: true
    pinned: false
    search: true
  page-navigation: true
  title: "COCOA: Collaborative Compendium on Analog Integrated Circuits"
  subtitle: ""
  abstract: ""
  repo-url: https://github.com/bmurmann/COCOA
  repo-branch: main
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  sharing: [twitter, facebook]
  reader-mode: true
  page-footer:
    left: |
      Curated by Boris Murmann
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - contents/contributors.qmd
    - contents/conventions.qmd
    - text: "---"
    - part: Learn to Crawl — Square-Law Transistors, Biasing and Small-Signal Analysis
      chapters:
      - contents/chapter1/introduction.qmd
    - text: "---"  
    - part: References
      chapters: 
        - references.qmd
    - text: "---"  


citation: true
license: CC-BY
filters:
  - custom_callout.lua
editor:
  render-on-save: true

bibliography: 
  - contents/chapter1/introduction.bib

#comments:
#  giscus:
#  repo: bmurmann/COCOA

format:
  html:
    reference-location: margin
    citation-location: margin

    theme: 
      light:
        - spacelab
        - style.scss
        - style-light.scss
      dark:
        - darkly
        - style.scss
        - style-dark.scss
    mainfont: Nunito
    fontsize: 1rem
    linkcolor: "#A51C30"
    urlcolor: "#A51C30"
    highlight-style: github
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: false
    citations-hover: false
    footnotes-hover: false
    fig-width: 8
    fig-height: 6
    number-depth: 3
    toc: true
    toc-depth: 4	
    citeproc: true
    #include-in-header:
    #  text: | 
    #    <script async src="https://www.googletagmanager.com/gtag/js?id=G-M21L0CBCVN"></script>
    #    <script src="/scripts/ai_menu/dist/bundle.js" defer></script>
    #    <script src="/scripts/ai_menu/dist/142.bundle.js" defer></script>
    #    <script src="/scripts/ai_menu/dist/384.bundle.js" defer></script>
    #    <script src="/scripts/ai_menu/dist/761.bundle.js" defer></script>
  
  pdf:
    documentclass: scrbook
    classoption: [abstract]
    keep-tex: false
    toc: true  # Table of Contents
    toc-depth: 3  # Depth of headings to include in TOC
    number-sections: true
    latex-engine: xelatex  # or pdflatex, lualatex, etc.
    geometry: margin=1in
    fontsize: 11pt
    papersize: letter  # or a4, etc.
    fig_caption: true
    link-citations: true
    citation_package: natbib  # or biblatex
    fig-cap-location: bottom
    tbl-cap-location: top

    # include-in-header:
    #   text: |
    #     \usepackage{fancyhdr}
    #     \usepackage{graphicx}
    #     \usepackage{mathptmx}
    #     \usepackage{fontspec}
    #     \usepackage{underscore}
    #     \usepackage[english]{babel}
    #     \usepackage{etoolbox}
    #     \usepackage{fontspec}
    #     \usepackage{newpxtext} % Palatino-like font
    #     \usepackage{hyperref} % For hyperlinks
    #     \usepackage{xcolor}
    #     \usepackage[format=plain,
    #         labelfont={bf,it},
    #         textfont=it, labelsep=space]{caption}

    #     \definecolor{crimson}{RGB}{165, 28, 48}

    #     \hypersetup{
    #       colorlinks=true, % Enable colored links
    #       linkcolor=crimson, % Color of internal links
    #       citecolor=crimson, % Color of citations
    #       urlcolor=crimson % Color of URLs
    #     }

    #     \patchcmd{\chapter}{\thispagestyle{plain}}{\thispagestyle{fancy}}{}{}

    #     %\newfontfamily\tocfont{Times New Roman}

    #     \let\endtitlepage\relax

    #     \AtBeginDocument{
    #       \begin{titlepage}
    #       \centering
    #       \vspace{-3em}
    #       %\includegraphics[width=\textwidth]{cover-image.pdf} % Adjust the size and path to your image
    #       \newpage
    #       {{\Huge\bfseries Analysis and Design of Elementary MOS Amplifier Stages}\\[1em] \Large The Modular Series of Microelectronic Device \& Circuit Design\par}

    #       \vspace*{\fill}
    #         {\large Curated by \\[.2cm] Prof. Boris Murmann \\[.2cm] University of Hawaii \\[1em] \normalsize {\itshape With special thanks to the community for their contributions and support.} \\[1em] \pagebreak \vfill \scriptsize Last Modified: \today\par \vfill}
    #       \vspace*{\fill}

    #       \end{titlepage}
          
    #       %\addtocontents{toc}{\tocfont}
    #     }

    #     \let\endtitlepage\relax

    #     \pagestyle{fancy}
    #     \fancyhf{} % Clear all header and footer fields
    #     \fancyhead[LE,RO]{\thepage} % Page number on the left on even pages, right on odd pages
    #     \fancyhead[RE,LO]{\nouppercase{\leftmark}} % Chapter name on both sides
    #     \renewcommand{\headrulewidth}{0.4pt}
    #     \renewcommand{\footrulewidth}{0pt}
        
    #     \fancypagestyle{plain}{%
    #       \fancyhf{} % clear all header and footer fields
    #       \fancyhead[LE,RO]{\thepage} % Page number
    #       \renewcommand{\headrulewidth}{0.4pt}
    #       \renewcommand{\footrulewidth}{0pt}
    #     }

    #     \addtokomafont{disposition}{\rmfamily\color{crimson}}
    #     \addtokomafont{chapter}{\color{crimson}}
    #     \addtokomafont{section}{\color{crimson}}

    #     % Define the abstract environment
    #     \newenvironment{abstract}{%
    #         \chapter*{\abstractname}%
    #         \addcontentsline{toc}{chapter}{\abstractname}%
    #         \small
    #     }{%
    #         \clearpage
    #     }
        
# crossref:
#   appendix-title: "Appendix"
#   appendix-delim: ":"

#   custom:
#     - kind: float
#       reference-prefix: Lab
#       key: labq
#       latex-env: lab

#     - kind: float
#       reference-prefix: Exercise
#       key: exr
#       latex-env: exr

#     - kind: float
#       reference-prefix: Video
#       key: vid
#       latex-env: vid
